env:
  browser: true
  # es2020: true
extends:
  - 'eslint:recommended'
  # - standard
parserOptions:
  ecmaVersion: 11
rules:
  arrow-body-style: 0
  brace-style: 0
  class-methods-use-this: 0
  consistent-return: 0
  import/prefer-default-export: 0
  max-len: 0
  no-case-declarations: 0
  no-console: 0 # 'warn' # disable for debug mode with `/* eslint-disable no-console */`
  no-debugger: 0 # 'warn' # disable for debug mode with `/* eslint-disable no-debugger */`
  no-param-reassign: 0
  no-shadow: 0
  object-curly-newline: 0
  operator-linebreak: 0
  padded-blocks: 0
  prefer-template: 0
  require-jsdoc: 0
  spaced-comment: 0
  quotes:
    - 'warn'
    - 'single'
  indent:
    - 'warn'
    - 2
    - SwitchCase: 1
  object-curly-spacing:
    - 'warn'
    - 'always'
  space-before-function-paren:
    - 'warn'
    - 'never'
  keyword-spacing:
    - 'warn'
    -
      before: true
      after: true
  no-unused-vars:
    - 'warn'
    -
      vars: 'local'
      varsIgnorePattern: '^_'
  semi:
    - 'warn'
    - 'always'
  no-trailing-spaces:
    - 2
    -
      skipBlankLines: true
